postgresql_settings: &postgresql_settings
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: postgres
  password: n2CH5nt+
  host: 35.188.173.154
  database: jaqnews

development:
  <<: *postgresql_settings

production:
  <<: *postgresql_settings

test:
  adapter: sqlite3
  pool: 5
  timeout: 5000
  database: db/test.sqlite3
